import React, { useState } from "react";
import axios from "axios";
import { useNavigate } from "react-router-dom";
import "./Register.css";

const Register = () => {
  const navigate = useNavigate();

  // State to manage form input values
  const [user, setUser] = useState({
    id: "", // Will be auto-generated by the backend
    firstname: "",
    lastname: "",
    username: "",
    phoneno: "",
    password: "",
    email: "",
    category: "CUSTOMER", // Default category
    deleteflag: false, // Default value
  });

  // State to manage errors
  const [error, setError] = useState("");

  // Handle input change
  const handleChange = (e) => {
    setUser({ ...user, [e.target.name]: e.target.value });
  };

  // Handle form submission
  const handleSubmit = async (e) => {
    e.preventDefault();

    // Basic validation
    if (
      !user.firstname ||
      !user.lastname ||
      !user.username ||
      !user.password ||
      !user.email ||
      !user.phoneno
    ) {
      setError("All fields are required!");
      return;
    }

    try {
      const response = await axios.post(
        "http://localhost:8080/Api/User/Register",
        user
      );
      console.log("Registration successful:", response.data);
      alert("Registration successful! Redirecting to Sign In...");
      navigate("/login"); // Redirect to Signin page after successful registration
    } catch (err) {
      console.error("Error during registration:", err);
      setError("Failed to register. Please try again.");
    }
  };

  return (
    <div className="register-container">
      <h2>Register</h2>
      {error && <p className="error">{error}</p>}
      <form onSubmit={handleSubmit}>
        <input
          type="text"
          name="firstname"
          placeholder="First Name"
          onChange={handleChange}
        />
        <input
          type="text"
          name="lastname"
          placeholder="Last Name"
          onChange={handleChange}
        />
        <input
          type="text"
          name="username"
          placeholder="Username"
          onChange={handleChange}
        />
        <input
          type="text"
          name="phoneno"
          placeholder="Phone Number"
          onChange={handleChange}
        />
        <input
          type="password"
          name="password"
          placeholder="Password"
          onChange={handleChange}
        />
        <input
          type="email"
          name="email"
          placeholder="Email"
          onChange={handleChange}
        />

        <label>Category:</label>
        <select name="category" value={user.category} onChange={handleChange}>
          <option value="CUSTOMER">Customer</option>
          <option value="TASKER">Tasker</option>
          <option value="BOTH">Both</option>
        </select>

        <button type="submit">Register</button>
      </form>
    </div>
  );
};

export default Register;
